app = "lacanian-actions"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "run actions --port 5055"

[[services]]
  processes = ["app"]
  internal_port = 5055
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[experimental]
  auto_rollback = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "chatdata"
  destination = "/app/persistent"
